### ISSUE TITLE
Excerise - Senior server-side position

### ISSUE THREAD

**Issue by playingwithtech** [ParcelVision/SLMM#6] opened 2017-06-14 12:10 UTC
1. What is expected of SLMM if position and lawn size not set before first move command is received?
There is no startup! SLMM cannot even try to fulfil requirements until at least one set request is received from a client.
**I would expect an error. e.g. 409 (Conflict).
2. I am assuming this is a fire-and-forget system. No response expected by Client to requests that could be processed but could also fail. i.e. no need for request Ids and request status.
**I would guess it just ignores any request that is invalid at the time of processing.
3. Due to concurrency requirements with multiple clients and existence of set request, a race condition exists where a set request may be queued before move requests intended for a previous state.
**I would guess it just ignores any request that is invalid at the time of processing.

I could make these decisions but since I am not the PO, any decision I make could be perfect or exactly wrong for the PO.

Regards,
Farhad Sheikhzeinoddin

**Comment by skleanthous** [comment] 2017-06-14 15:11
Hello Fahrad. To answer your questions:

1. This would be an unexpected situation. The expected behaviour from the PO perspective is that it should:
   1. Not crash the server (or raise an exception)
   1. At the bear minimum the error needs to be discoverable by the client. This means that there is not requirement to return an error from the API immediately (although it is fine to do so), the client must still be informed someway. How that happens is up to you.
1. I cannot comment on this. We want to test your analytical skills on this by drawing your conclusions from the information already provided. Please note that the reason we do this is that the senior developer would be required to participate in story grooming sessions along with the entire team and is expected to provide meaningful input on the stories being discussed.
1. This is a design decision. The PO is only interested in keeping the invariants in the [acceptance criteria](https://github.com/ParcelVision/SLMM#acceptance-criteria-1)

**Comment by skleanthous** [comment] 2018-10-09 19:28
This is for an older version of the exercise. Closing

**Closed by skleanthous** 2018-10-09 19:28 UTC
